server:
  addr: "0.0.0.0:8080"
  tokenDuration: 15m

db:
  driver: "mysql"
  host: "127.0.0.1"
  port: "3306"
  username: "root"
  password: ""
  source: "%s:%s@tcp(%s:%s)/simple_bank?parseTime=true"