version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: simple_bank
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
  api:
    container_name: simple_bank
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_SOURCE: "root:@tcp(mysql:3306)/simple_bank?parseTime=true"
    depends_on:
      - mysql
    command: [ "/app/main" ]
    entrypoint: [ "/app/wait-for.sh", "mysql:3306", "--", "/app/start.sh" ]