// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: entries.sql

package db

import (
	"context"
	"database/sql"
)

const createEntries = `-- name: CreateEntries :execresult
insert into entries (account_id, amount) values (?, ?)
`

type CreateEntriesParams struct {
	AccountID int64 `json:"accountID"`
	Amount    int64 `json:"amount"`
}

func (q *Queries) CreateEntries(ctx context.Context, arg CreateEntriesParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEntries, arg.AccountID, arg.Amount)
}
