// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddBalance(ctx context.Context, arg AddBalanceParams) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) (sql.Result, error)
	CreateEntries(ctx context.Context, arg CreateEntriesParams) (sql.Result, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteAccount(ctx context.Context, id sql.NullInt64) error
	FindUser(ctx context.Context, username string) (User, error)
	GetAccount(ctx context.Context, id sql.NullInt64) (Account, error)
	GetUser(ctx context.Context, id sql.NullInt64) (User, error)
	ListAccount(ctx context.Context, arg ListAccountParams) ([]Account, error)
}

var _ Querier = (*Queries)(nil)
