POST http://localhost:8080/account
Content-Type: application/json

{
  "accountOwner": "jrmarcco",
  "currency": "RMB"
}

###
GET http://localhost:8080/account/3

###
GET http://localhost:8080/account?pageNo=1&pageSize=10