# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: simple_bank
          MYSQL_USER: root
          MYSQL_PASSWORD: u2E3WWtgam
          MYSQL_ROOT_PASSWORD: u2E3WWtgam
        ports:
          - 31964:3306

    env:
      DB_DATABASE: simple_bank
      DB_USER: root
      DB_PASSWORD: u2E3WWtgam

    steps:
      - uses: actions/checkout@v3

      - name: Set up MySQL
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port 31964 -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -e 'create database ${{ env.DB_DATABASE }} collate utf8mb4_general_ci;'

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go

      - name: Install go-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin
          which migrate

      - name: Migrate Up
        run: make migrateup

      - name: Test
        run: go test -v ./...
