// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jrmarcco/go-backend-demo/db/ent/entries"
	"github.com/jrmarcco/go-backend-demo/db/ent/predicate"
)

// EntriesUpdate is the builder for updating Entries entities.
type EntriesUpdate struct {
	config
	hooks    []Hook
	mutation *EntriesMutation
}

// Where appends a list predicates to the EntriesUpdate builder.
func (eu *EntriesUpdate) Where(ps ...predicate.Entries) *EntriesUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetAccountID sets the "account_id" field.
func (eu *EntriesUpdate) SetAccountID(u uint64) *EntriesUpdate {
	eu.mutation.ResetAccountID()
	eu.mutation.SetAccountID(u)
	return eu
}

// AddAccountID adds u to the "account_id" field.
func (eu *EntriesUpdate) AddAccountID(u int64) *EntriesUpdate {
	eu.mutation.AddAccountID(u)
	return eu
}

// SetAmount sets the "amount" field.
func (eu *EntriesUpdate) SetAmount(i int64) *EntriesUpdate {
	eu.mutation.ResetAmount()
	eu.mutation.SetAmount(i)
	return eu
}

// AddAmount adds i to the "amount" field.
func (eu *EntriesUpdate) AddAmount(i int64) *EntriesUpdate {
	eu.mutation.AddAmount(i)
	return eu
}

// SetCreatedAt sets the "created_at" field.
func (eu *EntriesUpdate) SetCreatedAt(t time.Time) *EntriesUpdate {
	eu.mutation.SetCreatedAt(t)
	return eu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (eu *EntriesUpdate) SetNillableCreatedAt(t *time.Time) *EntriesUpdate {
	if t != nil {
		eu.SetCreatedAt(*t)
	}
	return eu
}

// SetUpdatedAt sets the "updated_at" field.
func (eu *EntriesUpdate) SetUpdatedAt(t time.Time) *EntriesUpdate {
	eu.mutation.SetUpdatedAt(t)
	return eu
}

// Mutation returns the EntriesMutation object of the builder.
func (eu *EntriesUpdate) Mutation() *EntriesMutation {
	return eu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EntriesUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	eu.defaults()
	if len(eu.hooks) == 0 {
		if err = eu.check(); err != nil {
			return 0, err
		}
		affected, err = eu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EntriesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = eu.check(); err != nil {
				return 0, err
			}
			eu.mutation = mutation
			affected, err = eu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(eu.hooks) - 1; i >= 0; i-- {
			if eu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = eu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EntriesUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EntriesUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EntriesUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (eu *EntriesUpdate) defaults() {
	if _, ok := eu.mutation.UpdatedAt(); !ok {
		v := entries.UpdateDefaultUpdatedAt()
		eu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *EntriesUpdate) check() error {
	if v, ok := eu.mutation.AccountID(); ok {
		if err := entries.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "Entries.account_id": %w`, err)}
		}
	}
	if v, ok := eu.mutation.Amount(); ok {
		if err := entries.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Entries.amount": %w`, err)}
		}
	}
	return nil
}

func (eu *EntriesUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   entries.Table,
			Columns: entries.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: entries.FieldID,
			},
		},
	}
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.AccountID(); ok {
		_spec.SetField(entries.FieldAccountID, field.TypeUint64, value)
	}
	if value, ok := eu.mutation.AddedAccountID(); ok {
		_spec.AddField(entries.FieldAccountID, field.TypeUint64, value)
	}
	if value, ok := eu.mutation.Amount(); ok {
		_spec.SetField(entries.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := eu.mutation.AddedAmount(); ok {
		_spec.AddField(entries.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := eu.mutation.CreatedAt(); ok {
		_spec.SetField(entries.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := eu.mutation.UpdatedAt(); ok {
		_spec.SetField(entries.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entries.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// EntriesUpdateOne is the builder for updating a single Entries entity.
type EntriesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntriesMutation
}

// SetAccountID sets the "account_id" field.
func (euo *EntriesUpdateOne) SetAccountID(u uint64) *EntriesUpdateOne {
	euo.mutation.ResetAccountID()
	euo.mutation.SetAccountID(u)
	return euo
}

// AddAccountID adds u to the "account_id" field.
func (euo *EntriesUpdateOne) AddAccountID(u int64) *EntriesUpdateOne {
	euo.mutation.AddAccountID(u)
	return euo
}

// SetAmount sets the "amount" field.
func (euo *EntriesUpdateOne) SetAmount(i int64) *EntriesUpdateOne {
	euo.mutation.ResetAmount()
	euo.mutation.SetAmount(i)
	return euo
}

// AddAmount adds i to the "amount" field.
func (euo *EntriesUpdateOne) AddAmount(i int64) *EntriesUpdateOne {
	euo.mutation.AddAmount(i)
	return euo
}

// SetCreatedAt sets the "created_at" field.
func (euo *EntriesUpdateOne) SetCreatedAt(t time.Time) *EntriesUpdateOne {
	euo.mutation.SetCreatedAt(t)
	return euo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (euo *EntriesUpdateOne) SetNillableCreatedAt(t *time.Time) *EntriesUpdateOne {
	if t != nil {
		euo.SetCreatedAt(*t)
	}
	return euo
}

// SetUpdatedAt sets the "updated_at" field.
func (euo *EntriesUpdateOne) SetUpdatedAt(t time.Time) *EntriesUpdateOne {
	euo.mutation.SetUpdatedAt(t)
	return euo
}

// Mutation returns the EntriesMutation object of the builder.
func (euo *EntriesUpdateOne) Mutation() *EntriesMutation {
	return euo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EntriesUpdateOne) Select(field string, fields ...string) *EntriesUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Entries entity.
func (euo *EntriesUpdateOne) Save(ctx context.Context) (*Entries, error) {
	var (
		err  error
		node *Entries
	)
	euo.defaults()
	if len(euo.hooks) == 0 {
		if err = euo.check(); err != nil {
			return nil, err
		}
		node, err = euo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EntriesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = euo.check(); err != nil {
				return nil, err
			}
			euo.mutation = mutation
			node, err = euo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(euo.hooks) - 1; i >= 0; i-- {
			if euo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = euo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, euo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Entries)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from EntriesMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EntriesUpdateOne) SaveX(ctx context.Context) *Entries {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EntriesUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EntriesUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (euo *EntriesUpdateOne) defaults() {
	if _, ok := euo.mutation.UpdatedAt(); !ok {
		v := entries.UpdateDefaultUpdatedAt()
		euo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *EntriesUpdateOne) check() error {
	if v, ok := euo.mutation.AccountID(); ok {
		if err := entries.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "Entries.account_id": %w`, err)}
		}
	}
	if v, ok := euo.mutation.Amount(); ok {
		if err := entries.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Entries.amount": %w`, err)}
		}
	}
	return nil
}

func (euo *EntriesUpdateOne) sqlSave(ctx context.Context) (_node *Entries, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   entries.Table,
			Columns: entries.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: entries.FieldID,
			},
		},
	}
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Entries.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entries.FieldID)
		for _, f := range fields {
			if !entries.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entries.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.AccountID(); ok {
		_spec.SetField(entries.FieldAccountID, field.TypeUint64, value)
	}
	if value, ok := euo.mutation.AddedAccountID(); ok {
		_spec.AddField(entries.FieldAccountID, field.TypeUint64, value)
	}
	if value, ok := euo.mutation.Amount(); ok {
		_spec.SetField(entries.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := euo.mutation.AddedAmount(); ok {
		_spec.AddField(entries.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := euo.mutation.CreatedAt(); ok {
		_spec.SetField(entries.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := euo.mutation.UpdatedAt(); ok {
		_spec.SetField(entries.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Entries{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entries.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
